### PR TITLE
Fix #3 - Preset Colors are string

### LINKED ISSUE #3: Changes for preset colors needed
After some clarification on the spec, we need to change how we manage preset colors, as the string is free to use for applications

### PR DESCRIPTION
**Pull request by julienduroure**
Preset color are String
Simple implementation where any string values are allowed.

### CODE REVIEW

**Comment by julienduroure** [comment]
@clbarnes If you are ok, can you please have a look on it?
Not sure if there is a simplier way to deserialize

**Comment by clbarnes** [comment]
I may have misunderstood the spec, but I thought that the specific numbered presets were all that was allowed, and the flexibility was in what a particular renderer called 'red'. If there's any information to the contrary that's fine!

**Comment by clbarnes** [comment]
Had a related conversation here https://github.com/obsidianmd/jsoncanvas/issues/37

**Comment by julienduroure** [comment]
Ahah, yes. Seems I misunderstood it.
Closing

**Pull request closed without merging**
